FROM dockerfile/ubuntu
MAINTAINER William Leung<superbill2012@qq.com>
RUN \
  add-apt-repository -y ppa:nginx/stable && \
  apt-get update && \
  apt-get install -y nginx && \
  rm -rf /var/lib/apt/lists/* && \
  echo "\ndaemon off;" >> /etc/nginx/nginx.conf && \
  chown -R www-data:www-data /var/lib/nginx

# Expose ports
EXPOSE 80
EXPOSE 443